name: CI
on:
  push:
    branches: [ "main" , "dev"]
  pull_request:
    branches: [ "main" ]
  paths:
    - '**/Cargo.toml'
    - '**/Cargo.lock'
env:
  CARGO_TERM_COLOR: always
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose